// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/waite-lee/sgn/pkg/app"
)

// Injectors from wire_inject.go:

func BuildAppContext() (*app.AppContext, error) {
	commandBuilder := app.NewCommandBuilder()
	appContext := app.NewAppContext(commandBuilder)
	return appContext, nil
}
