// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/waite-lee/nftserver/pkg/app"
)

// Injectors from inject_app.go:

func BuildAppContext() (*app.AppContext, error) {
	commandBuilder := app.NewCommandBuilder()
	appContext := &app.AppContext{
		CmdBuilder: commandBuilder,
	}
	return appContext, nil
}
