// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package nftv1

import (
	"github.com/waite-lee/nftserver/internal/apiserver/pkg/erc721"
	"github.com/waite-lee/nftserver/internal/common"
	"github.com/waite-lee/nftserver/pkg/blob/file"
	"github.com/waite-lee/nftserver/pkg/db/mongodb"
	"github.com/waite-lee/nftserver/pkg/eth"
	"github.com/waite-lee/nftserver/pkg/ipfs"
	"github.com/waite-lee/nftserver/pkg/mvc"
)

// Injectors from wire_inject.go:

func BuildNtfServiceV1() (*NftService, error) {
	etherScanOptions := _wireEtherScanOptionsValue
	client, err := erc721.GetClient(etherScanOptions)
	if err != nil {
		return nil, err
	}
	erc721Service := erc721.NewErc721Service(client, etherScanOptions)
	ethOptions := _wireEthOptionsValue
	ethclientClient, err := eth.GetClient(ethOptions)
	if err != nil {
		return nil, err
	}
	httpClientOptions := _wireHttpClientOptionsValue
	requestClient := mvc.NewRequestClient(httpClientOptions)
	ipfsOptions := _wireIpfsOptionsValue
	ipfsClient, err := ipfs.GetClient(requestClient, ipfsOptions)
	if err != nil {
		return nil, err
	}
	fileBlobStoreOptions := _wireFileBlobStoreOptionsValue
	blobStore := file.NewFileBlobStore(fileBlobStoreOptions)
	mongoOptions := _wireMongoOptionsValue
	mongoClient, err := mongodb.GetClient(mongoOptions)
	if err != nil {
		return nil, err
	}
	erc721TransferLogRepo := NewMongoErc721TransferLogRepo(mongoClient)
	nftTokenRepo := NewMongoDbNftTokenRepo(mongoClient)
	nftService := &NftService{
		Erc:        erc721Service,
		Client:     ethclientClient,
		IpfsClient: ipfsClient,
		Blobstore:  blobStore,
		LogRepo:    erc721TransferLogRepo,
		TokenRepo:  nftTokenRepo,
	}
	return nftService, nil
}

var (
	_wireEtherScanOptionsValue     = erc721.EsOptions
	_wireEthOptionsValue           = common.EthOptions
	_wireHttpClientOptionsValue    = common.HttpOptions
	_wireIpfsOptionsValue          = common.IpfsOptions
	_wireFileBlobStoreOptionsValue = common.FileOptions
	_wireMongoOptionsValue         = common.MongoOptions
)
