// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/waite-lee/nftserver/internal/apiserver"
	"github.com/waite-lee/nftserver/pkg/app"
	"github.com/waite-lee/nftserver/pkg/server"
)

// Injectors from inject_cmd.go:

func BuildCommands(ac *app.AppContext) AppCommands {
	testCmd := NewTestCmd()
	serverContext := server.NewServerContext()
	apiServer := apiserver.NewApiServer(serverContext, ac)
	apiServerOptions := _wireApiServerOptionsValue
	apiServerCmd := NewApiServerCmd(apiServer, apiServerOptions)
	nftPullCmd := NewNftPullCmd()
	appCommands := AppCommands{
		Test:      testCmd,
		ApiServer: apiServerCmd,
		NtfPull:   nftPullCmd,
	}
	return appCommands
}

var (
	_wireApiServerOptionsValue = apiserver.AsOptions
)
