// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package nftv1

import (
	"github.com/waite-lee/nftserver/internal/apiserver/ntf/erc721"
	"github.com/waite-lee/nftserver/pkg/eth"
)

// Injectors from inject_ntfv1.go:

func BuildNtfServiceV1() (*NftService, error) {
	etherScanOptions := _wireEtherScanOptionsValue
	client, err := erc721.GetClient(etherScanOptions)
	if err != nil {
		return nil, err
	}
	erc721Service := erc721.NewErc721Service(client, etherScanOptions)
	ethOptions := _wireEthOptionsValue
	ethclientClient, err := eth.GetClient(ethOptions)
	if err != nil {
		return nil, err
	}
	nftService := NewNtfService(erc721Service, ethclientClient)
	return nftService, nil
}

var (
	_wireEtherScanOptionsValue = erc721.EsOptions
	_wireEthOptionsValue       = eth.Options
)
