// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package blob

import (
	"github.com/SeeDAO-OpenSource/sgn/internal/common"
	"github.com/SeeDAO-OpenSource/sgn/pkg/blob/file"
)

// Injectors from wire_inject.go:

func BuildBlobServiceV1() *BlobService {
	fileBlobStoreOptions := _wireFileBlobStoreOptionsValue
	blobStore := file.NewFileBlobStore(fileBlobStoreOptions)
	blobService := NewBlobService(blobStore)
	return blobService
}

var (
	_wireFileBlobStoreOptionsValue = common.FileOptions
)
